apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: dockerapp
    new: app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: dockerapp
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
        - name: dockerapp
          image: akshayasgo/goapp
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: dockerser
spec:
  selector:
    app: dockerapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080